### PR TITLE
Refactor/animated layers

### PR DESCRIPTION
**Pull request by andredaa**

### CODE REVIEW

**Comment by andredaa** [comment]
@totev : i cannot understand why the unit test for the stormwater specs fails. would you explain them to me?

**Comment by totev** [comment]
It is failing because the store from store/index gets imported transitively by the cityPyOUserid function in authn.service. Some refactoring has to be done to decouple them :(

**Comment by andredaa** [comment]
> > It is failing because the store from store/index gets imported transitively by the cityPyOUserid function in authn.service. Some refactoring has to be done to decouple them :(
> 
> how did you read this from the error message or any other information given there? " TypeError: Cannot read properties of undefined (reading 'getters')"

Good - then anyway it is unrelated to the changes in this PR .

**Comment by totev** [comment]
Through the stack trace:

>       at Object.<anonymous> (src/store/index.ts:18:15)
>       at Object.<anonymous> (src/services/authn.service.ts:1:1)
>      at Object.<anonymous> (src/store/stormwater.ts:5:1)
>       at Object.<anonymous> (tests/unit/components/Scenario/StormwaterScenario.spec.ts:4:1)

It shouldn't import those stores. because in the test itself stormwater is being mocked.

**Comment by andredaa** [comment]
> because in the test itself stormwater is being mocked.

Ah - ok! makes sense!

**Pull request merged**
